# Generated by Django 3.0.14 on 2024-04-26 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/blog', verbose_name='تصویر')),
                ('slug', models.CharField(max_length=200, null=True, verbose_name='اسلاگ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seen', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید')),
                ('publish', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('statuse', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='draft', max_length=1, verbose_name='وضعیت انتشار')),
                ('tags', models.CharField(blank=True, max_length=1000, null=True, verbose_name='تگ ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_text', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=200, null=True, verbose_name='اسلاگ')),
                ('price', models.CharField(max_length=15, verbose_name='قیمت')),
                ('descryption', models.TextField(blank=True, verbose_name='توضیحات')),
                ('linq', models.URLField(verbose_name='لینک')),
                ('alt', models.CharField(max_length=50)),
                ('consent', models.IntegerField(verbose_name='میزان رضایتمندی مشتری ها')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('file', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('status', models.CharField(choices=[('p', 'publeshed'), ('d', 'draft')], default='draft', max_length=1, verbose_name='وضعیت انتشار')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='نمایش در گالری')),
                ('seen', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auth.Group', verbose_name='گروه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=25, verbose_name='متن هدر سایت')),
                ('content_h1_slider', models.CharField(max_length=25, verbose_name='متن بزرگ اسلایدر')),
                ('slider', models.ImageField(upload_to='images/slider')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute', to='blog.Attribute')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_product', to='blog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tags_BlogText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linq', models.URLField(null=True)),
                ('blog_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_blogtext', to='blog.Blog_Text')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='images/gallery/')),
                ('photo2', models.ImageField(upload_to='images/gallery/')),
                ('photo3', models.ImageField(upload_to='images/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.Product')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
    ]
