# Generated by Django 5.0.4 on 2024-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_attribute_id_alter_blog_text_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ImageField(upload_to='images/product', verbose_name='عکس'),
        ),
    ]
