# Generated by Django 5.0.4 on 2024-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consent',
            field=models.FloatField(verbose_name='میزان رضایتمندی مشتری ها'),
        ),
    ]
