# Generated by Django 5.0.4 on 2024-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_product_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='consent',
            field=models.FloatField(blank=True, null=True, verbose_name='میزان رضایتمندی مشتری ها'),
        ),
    ]
